name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os.os }}
    name: ${{ matrix.os.os }} (R=${{ matrix.R }}, Python=${{ matrix.python-version }})
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        R: ['release']
        os:
         - {os: ubuntu-latest, rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
         - {os: macos-latest}
         - {os: windows-latest}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: ${{ matrix.os.rspm }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for setuptools-scm

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os.os }}-pip-

      - name: Install macOS system dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install cairo pkg-config autoconf automake libtool

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}

      - name: Install dependencies
        run: |
          pip install .[test,copykat]

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'stringr'))" -e "remotes::install_github('navinlabcode/copykat')"

      - name: Check black formatting
        run: |
          black --check .

      - name: Test with pytest
        run: |
          pytest
